# Write Kubernetes Deployment Script
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers: 
      - name: book-catalog
        image: week07:1
        imagePullPolicy: Never
        env:
        - name: DATABASE_URL
          value: "postgresql://week07_ze2l_user:SgjpgiOuezs0lv6FxIK1eks6bQBzixPW@dpg-crs47htds78s73e0p320-a.oregon-postgres.render.com/week07_ze2l"
---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog
spec:
  selector:
    app: book-catalog
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000